sql query
orangeatom/rsvpu_informer_bot pull request #1
Opened 2017-04-29 15:20 UTC by orangeatom

2017-04-30 09:08 UTC, b0g3r requested changes

2017-04-30 09:08 UTC, b0g3r commented on sql.py
> +query_group = '''
запрос_группа
запрос чего?)

2017-04-30 09:08 UTC, b0g3r commented on telegram_bot.py
> +
а куда бот пропал?

2017-04-30 09:08 UTC, b0g3r commented on schedule.py
>  def schedule_group_query():
Я бы подумал над тем, чтобы всё это перенести в `модель` schedule, например. То есть добавить уровень абстракции, чтоб потом можно было удобно работать. Но это нужно подумать какие модели делать и какие у них будут "поля". В общем как наберешься смелости - замутим.

2017-05-01 20:17 UTC, b0g3r requested changes

2017-05-01 20:17 UTC, b0g3r commented on schedule.py
> +FormOfEducation = {4 : 'bachelor_full_day',
это ещё почему camel-case?

2017-05-01 20:17 UTC, b0g3r commented on schedule.py
> +senior_schedule_time = ('1️⃣ 08:00',
чем primary отличается от senior? Что это значит ваще?)

2017-05-01 20:17 UTC, b0g3r commented on schedule.py
> +def _format_query_schedule_group(date):
зачем нужна эта функция?

2017-05-03 09:51 UTC, b0g3r requested changes

2017-05-03 09:51 UTC, b0g3r commented on schedule.py
> +class ScheduleType():
google python enum

2017-05-03 09:51 UTC, b0g3r commented on schedule.py
> +class days():
почему  с маленькой?
скобки не нужны

2017-05-03 09:51 UTC, b0g3r commented on schedule.py
> +    """"""
Пустые докстринги - плохо

2017-05-03 09:51 UTC, b0g3r commented on schedule.py
> +def get_auditorium():
подумать над auditorium == room

2017-05-06 13:28 UTC, b0g3r requested changes

2017-05-06 13:28 UTC, b0g3r commented on schedule.py
> +    if type == ScheduleType.group:
а зачем здесь енам вообще, передавай строкой:
```
if type == 'group':
  pass
```

2017-05-06 13:28 UTC, b0g3r commented on schedule.py
> +    def tomorrow(self):
сделать методы @classmethod

2017-05-06 13:28 UTC, b0g3r commented on models.py
> +    state = IntegerField()
надо пилить кастомное поле

2017-05-06 13:28 UTC, b0g3r commented on schedule.py
> +        return {day: [pair_num, name, classroom, group]}
здесь по-любому должен быть тупл:
1. данные неконсистентны (разных типов)
2. структура статична (не будет меняться)

2017-05-06 13:28 UTC, b0g3r commented on schedule.py
> +FormOfEducation = {4: 'bachelor_full_day',
неиспользуемый код? Почему CamelCase'ом

2017-05-08 20:07 UTC, b0g3r requested changes

2017-05-08 20:07 UTC, b0g3r commented on schedule.py
> +                          password=os.environ['SCHEDULE_DB_PASS'],
почему? удалил из конфига ScheduleDatabase?
работа с конфигом должна быть в config.py, чтобы можно было менять конфиги как хочется: хардкод, переменные окружения, ямл, жсон, ини.... А работа в коде остается всё такой же: config.database_user

2017-05-08 20:07 UTC, b0g3r commented on schedule.py
> +FormOfEducation = {4: 'bachelor_full_day',
всё равно не понял че эт такое

2017-05-08 20:07 UTC, b0g3r commented on schedule.py
> +        """generate error"""
Заменять все заглушки комментариями типа
``` 
# TODO: сделать позже 
# FIXME: исправить позже
```
пайчарм умеет в их подсвечивание. Здесь нужен `FIXME: generate error`

2017-05-08 20:07 UTC, b0g3r commented on schedule.py
> +        cursor.execute("select Name from [Auditorium]")
все до единого sql-запросы должны быть вынесены в модуль
не сейчас, так потом)

2017-05-08 20:07 UTC, b0g3r commented on schedule.py
> +        cursor.execute(sql.schedule_teacher.format(date=day, id=teacher_id))
щас подумал, мне чего-то это не очень нравится
.format хорошо, но у pymssql.execute есть params, который работает по old-style (%s, %d) форматированию:
`c2.execute('SELECT * FROM %s WHERE salesrep=%s', params=('abc', 'cba')`

Тут есть два пути:
 - перейти на заложенный в pymssql внутренний формат с %s/%d и передачей params. Минусы: надо проверить работает ли `%(name)s` и переписать sql-запросы на old-style. Плюсы: внутри оно безопаснее
 - оставить всё как есть с форматом. Минусы: оно не использует безопасный форматтинг. Плюсы: оно работает уже и так.

2017-05-08 20:07 UTC, b0g3r commented on schedule.py
> +        cursor.execute(sql.schedule_teacher.format(date=day, id=teacher_id))
я откровенно хз что из этого лучше, решай сам

2017-05-08 20:07 UTC, b0g3r commented on models.py
> +class GroupFullDay(Model):
В чем отличие GroupFullDay от GroupHalfDay?

2017-05-08 20:07 UTC, b0g3r commented on schedule.py
> +db_value_form_of_education = {'full day': '4, 6',
что-то нехорошее стало с числами

2017-05-08 20:07 UTC, b0g3r commented on schedule.py
> +        """generate error"""
FIXME

2017-05-08 20:07 UTC, b0g3r commented on schedule.py
> +    while raw:
я кстати смотрю, ты тут везде fetchone используешь, а может fetchall?

2017-05-08 20:07 UTC, b0g3r commented on telegram_bot.py
> +bot = telebot.TeleBot(os.environ['TOKEN_BOT'])
config.token

2017-05-08 20:07 UTC, b0g3r commented on telegram_bot.py
> +print('run')
в if ... main:

2017-05-08 20:38 UTC, b0g3r requested changes

2017-05-08 20:38 UTC, b0g3r commented on schedule.py
>                            )
Переносу строки плохо.
Либо так:
```python3
# перенос по аргументам
connect = pymssql.connect(server=config.SCHEDULEDB.server,
                           password=config.SCHEDULEDB.pwd,
                           database=config.SCHEDULEDB.db,
                           user=config.SCHEDULEDB.user)
```
Либо так:
```python3
# перенос на другой уровень вложенности
connect = pymssql.connect(
    server=config.SCHEDULEDB.server,
    password=config.SCHEDULEDB.pwd,
    database=config.SCHEDULEDB.db,
    user=config.SCHEDULEDB.user
)
```
Смешивать: ни-ни

2017-05-08 20:38 UTC, b0g3r commented on schedule.py
> +db_value_form_of_education = {'full day': '4, 6',
И переносу строк тоже плохо

2017-05-08 20:38 UTC, b0g3r commented on schedule.py
> +def get_groups(group_substr=None, id=None, form_of_education=db_value_form_of_education['half day']):
Я бы херакнул так:
```python3
def get_groups(group_substr=None, id=None, form_of_education='half'):
    """return all groups or only the matching with math substr or set group id"""
    form_of_education = '5' if form_of_education == 'half' else '4, 6'
    cursor = connect.cursor(as_dict=True)
    if group_substr:
        cursor.execute("select Name from [Group] Where Lower(Name) LIKE '%{0}%' and FormOfEducation in ({1}})"
                       .format(group_substr, form_of_education))
    elif id:
        cursor.execute("select Name from [Group] where OID = {0}".format(id))
    else:
        cursor.execute("select Name from [Group] where FormOfEducation in ({0})".format(form_of_education))

    raw = cursor.fetchone()
    groups = [raw['Name']]
    while raw:
        raw = cursor.fetchone()
        if raw:
            groups.append(raw['Name'])
    return groups
```

2017-05-09 21:00 UTC, b0g3r requested changes

2017-05-09 21:00 UTC, b0g3r commented on config.py
> +                          )
э, скобка
говорил же

2017-05-09 21:00 UTC, b0g3r commented on schedule/__init__.py
> +                          )
скобка

2017-05-09 21:00 UTC, b0g3r commented on schedule/__init__.py
> +                              }
скобка

2017-05-09 21:00 UTC, b0g3r commented on schedule/__init__.py
> +    cursor = connect.cursor(as_dict=True)
а обработка ошибок?

2017-05-09 21:00 UTC, b0g3r commented on schedule/__init__.py
> +def __do_query(query):
а че два подчеркивания

2017-05-09 21:00 UTC, b0g3r commented on telegram_bot.py
> +    """Make something"""
охуенный докстринг
10/10

2017-05-15 19:54 UTC, b0g3r requested changes

2017-05-15 19:54 UTC, b0g3r commented on config.py
> +LOCALBASE = SqliteDatabase('base.db')
почему это тут?

2017-05-15 19:54 UTC, b0g3r commented on end_user/__init__.py
> +class EndUser:
Это что такое? Почему ни строчки документации?

2017-05-15 19:54 UTC, b0g3r commented on end_user/__init__.py
> +    # without logging
да я заметил

2017-05-15 19:54 UTC, b0g3r commented on models.py
> +localbase = LOCALBASE
очень странная констукция

2017-05-15 19:54 UTC, b0g3r commented on schedule_db/__init__.py
> +    68400, )
перенос скобки неправильный

2017-05-15 19:54 UTC, b0g3r commented on schedule_db/__init__.py
> +from schedule_db import sql
импорты разделяются на три группы, между ними - пустая строчка
- импорты стдлиб
- импорты внешних либ
- импорты модулей проекта

2017-05-15 19:54 UTC, b0g3r commented on schedule_db/__init__.py
> +    def week(self) -> list:
Days.week() ломает мне мозг
shift+f6 -> Calendar

2017-05-15 19:54 UTC, b0g3r commented on schedule_db/__init__.py
> +    cursor = __connect.cursor(as_dict=True)
обработка ошибок так и не появилась

2017-05-15 19:54 UTC, b0g3r commented on schedule_db/__init__.py
> +    cursor = __connect.cursor(as_dict=True)
Курсор определен выше

2017-05-15 19:54 UTC, b0g3r commented on schedule_db/__init__.py
> +def get_classrooms(group_substr=None):
так classrooms или group?

2017-05-15 19:54 UTC, b0g3r commented on telegram_bot.py
> +    # todo
todo что?
пустой туду - тоже самое что и его отсутствие

2017-05-15 19:54 UTC, b0g3r commented on end_user/__init__.py
> +        elif query:
что за query?

2017-05-15 19:54 UTC, b0g3r commented on end_user/__init__.py
> +        self.__increment_query()
код, который повторяется в трех методах

2017-05-15 19:54 UTC, b0g3r commented on end_user/__init__.py
> +        return self.user.state
здесь явно нужен property

2017-05-15 19:54 UTC, b0g3r commented on end_user/__init__.py
> +        self.user.timeline_login = login
что такое login?

2017-05-16 07:09 UTC, orangeatom commented on schedule_db/__init__.py
> +from schedule_db import sql
окей, спасибо, интересно и полезно

2017-05-16 07:10 UTC, orangeatom commented on end_user/__init__.py
> +        self.user.timeline_login = login
логин, как не странно, там через OAuth2.0 дальше магия пойдет с этим

2017-05-16 07:11 UTC, orangeatom commented on end_user/__init__.py
> +        elif query:
это для обработчиков инлайн вызовов, там отправляется query объект который содержит в себе данные только from_user

2017-05-16 07:11 UTC, orangeatom commented on config.py
> +LOCALBASE = SqliteDatabase('base.db')
а где еще?

2017-05-16 10:34 UTC, b0g3r commented on config.py
> +LOCALBASE = SqliteDatabase('base.db')
В каком-нибудь models.py или где оно там нужно

2017-05-16 10:35 UTC, b0g3r commented on end_user/__init__.py
> +        self.user.timeline_login = login
а что тогда такое timeline-login? почему он timeline?

2017-05-16 20:08 UTC, orangeatom commented on telegram_bot.py
> +    # todo
выше описано)

2017-05-16 20:09 UTC, orangeatom commented on schedule_db/__init__.py
> +    cursor = __connect.cursor(as_dict=True)
курсор выше уберу, с обработкой пока повременю

2017-05-19 15:19 UTC, b0g3r requested changes

2017-05-19 15:19 UTC, b0g3r commented on telegram_bot.py
> +localbase = config.LOCALBASE
опять

2017-05-19 15:19 UTC, b0g3r commented on telegram_bot.py
> +important_links = '''
куда-нибудь все эти константы в другое место вынести, чего они место занимают

2017-05-19 15:19 UTC, b0g3r commented on init.py
> +localbase = LOCALBASE
опять это

2017-05-19 15:19 UTC, b0g3r commented on schedule_db/__init__.py
> +    cursor = __connect.cursor(as_dict=True)
ты её все равно делаешь, только в каждой функции отдельно

2017-05-19 15:19 UTC, b0g3r commented on state/__init__.py
> +# todo
todo что?

2017-05-19 15:19 UTC, b0g3r commented on telegram_bot.py
> +    # todo
не понимаю

2017-05-19 15:19 UTC, b0g3r commented on telegram_bot.py
> +@bot.message_handler(func=lambda msg: user.User(msg).get_state() == state.states['StartMenu'],
всю эту лямбду сделать нормальной такой функцией, куда передавать msg и expected_state, а она пусть возвращает true/false

2017-06-07 20:14 UTC, b0g3r requested changes

2017-06-07 20:14 UTC, b0g3r commented on schedule_db/sql.py
> +select Course from [Group]
чего sql так по разному отформатирован?

2017-06-07 20:14 UTC, b0g3r commented on texts.py
> +TIMETABLE = 'Расписание звонков ⏰'
почему одно - uppercase, а другое - в lowercase

2017-11-22 08:38 UTC, closed without merging